# This is a basic workflow to help you get started with Actions

name: Deploy Project to Amazon EC2

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: frontend server CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.FRONTEND_USERNAME }}
          key: ${{ secrets.FRONTEND_KEY }}
          script: |
            sh deploy.sh

      - name: stop server via ssh and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sh deploy.sh
