# This is a basic workflow to help you get started with Actions

on:
  push:
    branches:
      - release

name: Deploy Project to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: set package 
        run: yarn install
        shell: bash

      - name: Build Project
        run: yarn build
        shell: bash
